version: '3'
services:

  backend:
    build: ./backend
    container_name: friends-finder-backend
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: friends-finder-frontend
    ports:
      - "8080:8080"
    links:
      - backend