version: '3'
services:

  friends-finder-app:
    build: ./friends-finder-app
    container_name: friends-finder-app
    ports:
      - "8081:8081"

  friends-finder-client:
    build: ./friends-finder-client
    container_name: friends-finder-client
    ports:
      - "8080:8080"
    links:
      - friends-finder-app